module(
    name = "openlocationcode",
    version = "1.0",
)

# bazel-skylib required by #@io_bazel_rules_closure.
# https://github.com/bazelbuild/bazel-skylib
bazel_dep(name = "bazel_skylib", version = "1.7.1")

# googletest required by c/BUILD.
# https://github.com/google/googletest
bazel_dep(name = "googletest", version = "1.15.2")

bazel_dep(name = "rules_rust", version = "0.58.0")

bazel_dep(name = "protobuf", version = "27.0", repo_name = "com_google_protobuf")

crate = use_extension("@rules_rust//crate_universe:extension.bzl", "crate")
crate.from_cargo(
    name = "crates",
    cargo_lockfile = "//rust:Cargo.lock",
    manifests = ["//rust:Cargo.toml"],
)
crate.annotation(
    crate = "open-location-code",
    rustc_flags = ["-Zunstable-options"],
)
use_repo(crate, "crates")
