name: CI
on: [push, pull_request]
jobs:
  # C implementation. Lives in c/, tested with bazel.
  test-c:
    runs-on: ubuntu-latest
    env:
      OLC_PATH: c
    steps:
      - uses: actions/checkout@v2
      - name: test
        run: bazel test --test_output=all ${OLC_PATH}:all
      - name: check formatting
        run: cd ${OLC_PATH} && bash clang_check.sh
        
  # C++ implementation. Lives in cpp/, tested with bazel.
  test-cpp:
    runs-on: ubuntu-latest
    env:
      OLC_PATH: cpp
    steps:
      - uses: actions/checkout@v2
      - name: test
        run: bazel test --test_output=all ${OLC_PATH}:all
      - name: check formatting
        run: cd ${OLC_PATH} && bash clang_check.sh
        
  # Dart implementation. Lives in dart/.
  test-dart:
    runs-on: ubuntu-latest
    env:
      OLC_PATH: dart
    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1
      - name: test
        run: |
          cd ${OLC_PATH}
          pub get && pub run test
          bash checks.sh

  # Go implementation. Lives in go/. Tests fail if files have not been formatted with gofmt.
  test-go:
    runs-on: ubuntu-latest
    env:
      OLC_PATH: go
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - name: test
      run: |
        cd ${OLC_PATH}
        diff -u <(echo -n) <(gofmt -d -s ./)
        go test -bench=. ./ -v
    - name: test-gridserver
      run: |
        cd tile_server/gridserver
        go test ./ -v
        
  # Java implementation. Lives in java/, tested with bazel and maven.     
  test-java:
    runs-on: ubuntu-latest
    env:
      OLC_PATH: java
    strategy:
      matrix:
        java: [ '8', '11', '16', '17' ]
    name: test-java-${{ matrix.java }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
      - name: test
        run: bazel test --test_output=all ${OLC_PATH}:all && cd ${OLC_PATH} && mvn package
